name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: rabel798679
          key: ${{ secrets.AZURE_SSH_KEY }}
          script: |
             where.exe git
