name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: rabel798679
          key: ${{ secrets.AZURE_SSH_KEY }}
          capture_stdout: true
          script: |
            echo ===== DEBUG START =====

            echo Current directory:
            cd
            pwd

            echo.
            echo Git location:
            where.exe git

            echo.
            echo Git version:
            git --version

            echo.
            echo Project directory:
            cd C:\Users\rabel798679\Projects\lab-project

            echo.
            echo Latest commit on VM:
            git log --oneline -1

            echo ===== DEBUG END =====
            
